
force_cast:
  severity: error
force_try:
  severity: error
force_unwrapping:
  severity: error
implicitly_unwrapped_optional:
  severity: error

vertical_whitespace:
  max_empty_lines: 2
  severity: warning

function_body_length:
  - 10
  - 20

type_body_length:
  - 200
  - 400

file_length:
  warning: 300
  error: 1000

identifier_name:
  min_length:
    warning: 0
    error: 0
  excluded:
    - id
    - URL
    - x
    - y

